In [2]:
from sklearn.preprocessing import LabelEncoder

colors = ["Red", "Blue", "Green", "Blue"]

encoder = LabelEncoder()
encoded_colors = encoder.fit_transform(colors)

print(encoded_colors)

[2 0 1 0]


In [16]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
# Convert to 2D array (required)
colors = np.array(["Red", "Blue", "Green", "Blue", "Red", "Red", "Red", "Blue"]).reshape(-1, 1)

encoder = OneHotEncoder(sparse_output=False)  # return normal array
encoded_colors = encoder.fit_transform(colors)
# print(encoder.get_feature_names_out())
df = pd.DataFrame(encoded_colors, columns=encoder.get_feature_names_out())
# print(df)


df['colors'] = ["Red", "Blue", "Green", "Blue", "Red", "Red", "Red", "Blue"]
print(df)

   x0_Blue  x0_Green  x0_Red colors
0      0.0       0.0     1.0    Red
1      1.0       0.0     0.0   Blue
2      0.0       1.0     0.0  Green
3      1.0       0.0     0.0   Blue
4      0.0       0.0     1.0    Red
5      0.0       0.0     1.0    Red
6      0.0       0.0     1.0    Red
7      1.0       0.0     0.0   Blue


In [13]:
encoded_colors

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [14]:
import pandas as pd

# Create dataset
data = {
    "Customer_ID": ["C001", "C002", "C003", "C004", "C005"],
    "Gender": ["Male", "Female", "Female", "Male", "Male"],
    "City": ["Delhi", "Mumbai", "Delhi", "Chennai", "Mumbai"],
    "Purchased": ["Yes", "No", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
df

Original DataFrame:


,Customer_ID,Gender,City,Purchased
0,C001,Male,Delhi,Yes
1,C002,Female,Mumbai,No
2,C003,Female,Delhi,Yes
3,C004,Male,Chennai,No
4,C005,Male,Mumbai,Yes


In [2]:
from sklearn.preprocessing import LabelEncoder

# Copy dataframe to avoid mutation
df_label = df.copy()

label_encoder = LabelEncoder()

# Encode categorical columns
df_label["Gender"] = label_encoder.fit_transform(df_label["Gender"])
df_label["City"] = label_encoder.fit_transform(df_label["City"])
df_label["Purchased"] = label_encoder.fit_transform(df_label["Purchased"])

print("\nLabel Encoded DataFrame:")
print(df_label)


Label Encoded DataFrame:
  Customer_ID  Gender  City  Purchased
0        C001       1     1          1
1        C002       0     2          0
2        C003       0     1          1
3        C004       1     0          0
4        C005       1     2          1


In [33]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Separate features and target
X = df[["Gender", "City"]]
y = df["Purchased"]



# Define column transformer
ct = ColumnTransformer(
    transformers=[
        ("onehot", OneHotEncoder( sparse_output=False), ["Gender", "City"])
    ],
    # remainder="drop"
)

ct

# Fit and transform
X_encoded = ct.fit_transform(X)


In [36]:

# Convert to DataFrame with proper column names
encoded_columns = ct.named_transformers_["onehot"].get_feature_names_out(["Gender", "City"])
X_encoded_df = pd.DataFrame(X_encoded, columns=encoded_columns)

print("\nOne-Hot Encoded Features:")
print(X_encoded_df)

print(X_encoded)
# df


One-Hot Encoded Features:
   Gender_Female  Gender_Male  City_Chennai  City_Delhi  City_Mumbai
0            0.0          1.0           0.0         1.0          0.0
1            1.0          0.0           0.0         0.0          1.0
2            1.0          0.0           0.0         1.0          0.0
3            0.0          1.0           1.0         0.0          0.0
4            0.0          1.0           0.0         0.0          1.0
[[0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 1. 0.]
 [0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 1.]]


array([[0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 1.]])